### ISSUE TITLE
Do you have any code/design about homa?

### ISSUE THREAD

**Issue by zpk1203** [PlatformLab/Homa#1]
I'm searching a good transport protocol.
I wanna know more about homa, like whether there's a finished version.

**Comment by yilongli** [comment]
You can find the Homa paper on arxiv: https://arxiv.org/abs/1803.09615

We have an implementation of Homa inside RAMCloud, which is used for the evaluation in the paper. We are currently working on pulling that implementation out of RAMCloud as a separate module. This is the purpose of this repo. Note that this will be a userspace implementation which relies on userspace kernel-bypass solutions such as DPDK. We also plan to have a in-kernel implementation for Homa eventually, though we haven't started working on that.

**Comment by behnamm** [comment]
For more information and learning about Homa, you can read our research paper on arxiv: https://arxiv.org/abs/1803.09615

At the moment, there are a simulation and an implementation of Homa available on github. You can find the simulation source here: https://github.com/PlatformLab/HomaSimulation/tree/omnet_simulations/RpcTransportDesign/OMNeT%2B%2BSimulation

The current implementation for Homa is tied to RAMCloud source code and you can find it on the homa-transport branch of RAMCloud repo:
https://github.com/PlatformLab/RAMCloud/tree/homa-transport/src

Unfortunately, we don't have a stand alone implementation for Homa outside of RAMCloud yet, but we are currently working on that. This repository will eventually contain that stand alone implementation. Stay tuned!

**Comment by zpk1203** [comment]
I'm learning
Thanks for your time and info
